parameter settings and language support
eriksl/streamproxy pull request #9
Opened 2019-02-22 16:40 UTC by anudanan

The streamproxy.conf parameter are not setable with transcodingsetup plugin and OWIF setting of transcoding setup

A new parameter audiolang in streamproxy.conf is available for setting the language for filetranscoding.
The parameter ist setable with transcodingsetup. The value auto means that streamproxy use the language letters of config.osd.language of enigma setting.
If no language is available in the stream the first AC3 Audio or Audio is used
Detection of teletext and subtitle now with description IDs in PMT

2019-02-23 09:23 UTC, eriksl commented
There are a few things that need to be changed

1) set your tabstop to 4 and you won't need to change whitespace
2) don't mix different changes in one commit, i.e. where you change the format string doesn't belong in the same commit

If you address this, I will merge it.

2019-02-23 11:29 UTC, anudanan commented
Thx for information. I will see later on this weekend. I must do some thing outside in the garden ;-)

I woundert me about the different indent but now it is clear (tabstop 4). Is the use of tabstop 4 recommended in all openpli sourcecode?
In some modules I don´t have seen different indents with the default tabstopp 8 but I think there are no space and onyl tabs inside

2019-02-23 13:54 UTC, eriksl commented
Indent is per file historical, but we try to maintain tabstop = 4 (in the C++ files). Python is another story.

2019-02-23 21:00 UTC, anudanan commented
I´ve changed now the files and I hope they are ok for you. I use now tapstop 4

I´ve additional added the feature for using the enigma settings for autolanguage with 4 prios,the demand came from the openpli forum. If the audiolang parameter in streamproxy.conf is empty or xxx (that is the default) then the enigma config.autolanguage,audio1-4 are used for language selection.
On my box it works perfectly now for recorded movies.

2019-02-24 09:21 UTC, eriksl requested changes

2019-02-24 09:21 UTC, eriksl commented on src/filetranscoding-broadcom.cpp
> +	int			encoder_fd, timeout;
whitespace change

2019-02-24 09:21 UTC, eriksl commented on src/filetranscoding-broadcom.cpp
> +	struct pollfd		pfd[2];
ws

2019-02-24 09:21 UTC, eriksl commented on src/filetranscoding-broadcom.cpp
> +	int			time_offset_s = 0;
ws

2019-02-24 09:21 UTC, eriksl commented on src/filetranscoding-broadcom.cpp
> +	const char *	http_ok		=	"HTTP/1.1 200 OK\r\n";
ws

2019-02-24 09:21 UTC, eriksl commented on src/filetranscoding-broadcom.cpp
> +		Util::vlog("FileTranscodingBroadcom: pid[%s] = %d", it->first.c_str(), it->second);
Unrelated change

2019-02-24 09:21 UTC, eriksl commented on src/mpegts.cpp
> +			//Util::vlog("MpegTS::read_pmt > reserved_1: %x", pmt_header->reserved_1);
Unrelated change

2019-02-24 09:21 UTC, eriksl commented on src/mpegts.cpp
> +			//Util::vlog("MpegTS::read_pmt: > unused: %x", pmt_header->unused);
Unrelated

2019-02-24 09:21 UTC, eriksl commented on src/mpegts.cpp
> +			//Util::vlog("MpegTS::read_pmt: > reserved_2: %x", pmt_header->reserved_2);
Unrelated

2019-02-24 09:21 UTC, eriksl commented on src/mpegts.cpp
> +				//Util::vlog("MpegTS::read_pmt: reserved 1: %x", es_entry->reserved_1);
Unrelated

2019-02-24 09:21 UTC, eriksl commented on src/mpegts.cpp
> +				//Util::vlog("MpegTS::read_pmt: reserved 2: %x", es_entry->reserved_2);
Unrelated

2019-02-24 09:21 UTC, eriksl commented on src/mpegts.cpp
> +				//Util::vlog("MpegTS::read_pmt: unused: %x", es_entry->unused);
Unrelated

2019-02-24 09:21 UTC, eriksl commented on src/mpegts.cpp
> +								//		 ds_a->lang[1], ds_a->lang[2], ds_a->code);
Whitespace

2019-02-24 09:21 UTC, eriksl commented on src/mpegts.h
> +		bool		request_time_seek;
whitespace

2019-02-24 09:21 UTC, eriksl commented on src/mpegts.h
> +		bool		is_time_seekable;
whitespace

2019-02-24 09:21 UTC, eriksl commented on src/streamproxy.conf
> +# all neccessary transcoding parameter
I'd like to have the comments in the config file in another, separate commit.

2019-02-24 09:21 UTC, eriksl commented on src/streamproxy.cpp
> -			("foreground,f",	bpo::bool_switch(&Util::foreground)->implicit_value(true),		"run in foreground (don't become a daemon)")
all whitespace changes

2019-02-24 09:21 UTC, eriksl commented on src/streamproxy.cpp
> -		config_map["group"]			= ConfigValue(require_auth_group);
ws

2019-02-24 09:21 UTC, eriksl commented on src/streamproxy.cpp
> -		config_map["size"]			= ConfigValue(option_default_size);
ws

2019-02-24 09:21 UTC, eriksl commented on src/streamproxy.cpp
> -		config_map["level"]			= ConfigValue(option_default_level);
ws

2019-02-24 09:26 UTC, eriksl requested changes

2019-02-24 09:26 UTC, eriksl commented on src/mpegts.cpp
> +		//Util::vlog("MpegTS::read_table: correct packet with pid: 0x%x, %s", pid, packet.header.pusi ? "start" : "continuation");
unrelated

2019-02-24 09:26 UTC, eriksl commented on src/mpegts.cpp
> +				Util::vlog("MpegTS::read_table: reserved != 0x03: 0x%x", table->reserved);
unrelated

2019-02-24 09:26 UTC, eriksl commented on src/mpegts.cpp
> +				Util::vlog("MpegTS::read_table: section length unused != 0x00: 0x%x", table->section_length_unused);
unrelated

2019-02-24 09:26 UTC, eriksl commented on src/mpegts.cpp
> +		Util::vlog("MpegTS::read_table: crc mismatch: my crc: 0x%x, their crc: 0x%x", my_crc.checksum(), their_crc);
unrelated

2019-02-24 09:26 UTC, eriksl commented on src/mpegts.cpp
> +			//Util::vlog("MpegTS::read_pat > program: %d -> pid 0x%x", program, pid);
unrelated

2019-02-24 09:26 UTC, eriksl commented on src/mpegts.cpp
> +				//Util::vlog("MpegTS::read_pat > reserved != 0x07: 0x%x", entry[current].reserved);
unrelated

2019-02-24 09:26 UTC, eriksl commented on src/mpegts.cpp
> +			//Util::vlog("MpegTS::read_pmt > reserved_1: 0x%x", pmt_header->reserved_1);
unrelated

2019-02-24 09:26 UTC, eriksl commented on src/mpegts.cpp
> +		//Util::vlog("MpegTS::read_pmt: > pcr_pid: 0x%x", pcr_pid);
unrelated

2019-02-24 09:26 UTC, eriksl commented on src/mpegts.cpp
> +			//Util::vlog("MpegTS::read_pmt: > unused: 0x%x", pmt_header->unused);
unrelated

2019-02-24 09:26 UTC, eriksl commented on src/mpegts.cpp
> +			//Util::vlog("MpegTS::read_pmt: > reserved_2: 0x%x", pmt_header->reserved_2);
unrelated

2019-02-24 09:26 UTC, eriksl commented on src/mpegts.cpp
> +				//Util::vlog("MpegTS::read_pmt: reserved 1: 0x%x", es_entry->reserved_1);
unrelated

2019-02-24 09:26 UTC, eriksl commented on src/mpegts.cpp
> +			//Util::vlog("MpegTS::read_pmt: >> pid: 0x%x, %d", es_pid, es_pid);
unrelated

2019-02-24 09:26 UTC, eriksl commented on src/mpegts.cpp
> +				//Util::vlog("MpegTS::read_pmt: reserved 2: 0x%x", es_entry->reserved_2);
unrelated

2019-02-24 09:26 UTC, eriksl commented on src/mpegts.cpp
> +						//Util::vlog("MpegTS::read_pmt: >>> descriptor id: 0x%x", ds_entry->id);
unrelated

2019-02-24 09:28 UTC, eriksl commented on src/mpegts.cpp
> +				//Util::vlog("MpegTS::read_pmt: unused: 0x%x", es_entry->unused);
unrelated

2019-02-24 09:28 UTC, eriksl requested changes

2019-02-24 09:28 UTC, eriksl commented on src/streamproxy.cpp
> +		if(settings.exists("config.osd.language") && ((option_default_audiolang.compare("xxx")==0) || option_default_audiolang.empty()))
add spaces
)==0
) == 0

2019-02-24 09:36 UTC, eriksl commented on src/configmap.cpp
> -	int_value = Util::string_to_int(in);
unrelated

2019-02-24 09:36 UTC, eriksl commented on src/streamproxy.cpp
> -	//Util::vlog("streamproxy: audiolang: %s", audiolang.c_str());
unrelated

2019-02-24 09:38 UTC, eriksl requested changes

2019-02-24 09:38 UTC, eriksl commented on src/streamproxy.cpp
> -	Util::vlog("streamproxy: audiolang: %s", audiolang.c_str());
unrelated

2019-02-24 09:39 UTC, eriksl requested changes

2019-02-24 09:39 UTC, eriksl commented on src/mpegts.cpp
> +    boost::split(autolangprios_vector, audiolang, boost::is_any_of("/"));
indented with spaces

2019-02-24 09:39 UTC, eriksl commented on src/mpegts.cpp
> +																						// jjj: Prio 4 languages
extra empty line

2019-02-24 09:39 UTC, eriksl commented on src/mpegts.cpp
> +                    if(boost::starts_with(stream_language, singlelang))					// if selected is prefix
idented with spaces

2019-02-24 09:39 UTC, eriksl commented on src/mpegts.cpp
> +	int			attempt, programinfo_length, esinfo_length;
ws

2019-02-24 09:39 UTC, eriksl commented on src/mpegts.cpp
> +	int			es_pid, es_data_length, es_data_skip, es_data_offset;
ws

2019-02-24 09:39 UTC, eriksl commented on src/mpegts.cpp
> +	int			ds_data_skip, ds_data_offset;
ws

2019-02-24 09:39 UTC, eriksl commented on src/mpegts.cpp
> +	string     	audiolang_choose, audiolang_fallback;
indented with spaces

2019-02-24 09:39 UTC, eriksl commented on src/mpegts.cpp
> -                                        }
ws

2019-02-24 09:39 UTC, eriksl commented on src/mpegts.cpp
> -                        }
ws

2019-02-24 09:39 UTC, eriksl commented on src/mpegts.cpp
> -                                }
ws

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> - 		string                                                                  option_default_audiolang;
whitespace

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> +			("group,g",			bpo::value<string>(&require_auth_group),					"require streaming users to be member of this group")
ws

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> +			("listen,l",		bpo::value<StringVector>(&listen_parameters),				"listen to tcp port with default action")
ws

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> +			("size,s",			bpo::value<string>(&option_default_size),					"default transcoding frame size")
ws

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> +			("bitrate,b",		bpo::value<string>(&option_default_bitrate),				"default transcoding bit rate")
ws

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> +			("profile,P",		bpo::value<string>(&option_default_profile),				"default transcoding h264 profile")
ws

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> +			("level,L",			bpo::value<string>(&option_default_level),					"default transcoding h264 level")
ws

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> +			("bframes,B",		bpo::value<string>(&option_default_bframes),				"default transcoding h264 b frames")
ws

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> +			("audiolang,A",		bpo::value<string>(&option_default_audiolang),				"default audio language")
ws

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> +			("webifport,a",		bpo::value<string>(&option_webifport),						"tcp port OpenWebIf is listening on")
ws

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> -		config_map["group"]		= ConfigValue(require_auth_group);
ws

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> -		config_map["size"]		= ConfigValue(option_default_size);
ws

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> +		config_map["group"]			= ConfigValue(require_auth_group);
ws

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> +		config_map["size"]			= ConfigValue(option_default_size);
ws

2019-02-24 09:39 UTC, eriksl commented on src/streamproxy.cpp
> +		config_map["level"]			= ConfigValue(option_default_level);
ws

2019-02-24 09:43 UTC, anudanan commented on src/streamproxy.conf
> +# all neccessary transcoding parameter
How can I do a separate commit from now? Make a little change in streamproxy.conf and than a single commit?

2019-02-24 09:43 UTC, anudanan commented
The changes with %x to 0x%x in debug output I have done for better reading that the value is hex. 
Is that not ok for you?

With withspace I will see what I cant do to make you happy. I will see to make there now difference, but it take some time

But one additional questions to the pullrequest.

2019-02-24 09:46 UTC, eriksl commented
I'd like to see about four commits from you:

1) first all whitespace changes, where necessary (I believe in the end none of them is required, but I am not sure). Make sure spaces are never used for indenting (see change requests). Set your editor to show spaces and check if they're never in the indenting section of a line. They also can't be at the end of a line.

2) first generic change commit (like: add 0x to debugging hex output)

3) second generic change commit (...)

4) first primary commit (like add audio selection on file transcoding), with all related changes in all files

5) second primary commit (like add audio selection on live transcoding), with all related changes in all files

This way, if someone needs to do a git blame at some point, they can immediately see what primary commit changed the lines.

Please try, if you can't, supply a complete patch and I will process it into commits.

2019-02-24 09:49 UTC, eriksl commented
Please note: mixing generic changes plus whitespace change with functional changes make it hard to spot what actually has changed within a commit, that's why it's good practise to separate them. In this case you'll see that if you split whitespace, the remaining commit will be quite small (which is good).

2019-02-24 09:53 UTC, anudanan commented
How is the best way now?Reverting all commits and make new commits are only new commits in above steps?
 I have not done step 5. Language selection in streamproxy is only for filetranscoding today.
 I´m a beginner in opensource project rules ;-)

2019-02-24 10:10 UTC, eriksl commented
I don't have much experience in github, I am normally using git from the command line. Then there is an option to selectively add chunks to a commit (it's called git add -p). With that option it's very simple to do. I am not sure if it can be done using github.

That's why I say if you don't manage, send the complete patch to me and I'll do it with the command line git.

2019-02-24 11:17 UTC, anudanan commented
I also use git on commandline and make a push to github. 

Is it ok if I make from now the commits in different steps or must I start from a clean repro copy of your streamproxy source to have the clean steps for you? I think my older commits are always in the git history if your merge or make you cherry-picks of only  of the new  files which are ok for you?

2019-02-24 12:39 UTC, anudanan commented
I have now three changing steps on my local system
1. Debugging changes
2. audiolanguage support for filetranscoding
3. changes of streamproxy.conf

Now I can make 3 commits to github  but then the last not nice commits are seen for ever
I also kann reset my local git to your master and make three new commits. I think that is cleaner but what must I do with the pullrequest? Closing and make new request after the 3 commits?

2019-02-24 14:03 UTC, closed without merging

2019-02-24 14:57 UTC, anudanan commented
I´ve made a repro reset to your master branch on my local system  and a push to github. This closed these pullrequest here (logical because the commits are deleted) . Now different commits and a new pullrequest are on the road.

2019-03-02 09:55 UTC, eriksl commented
ok

2019-03-02 10:00 UTC, eriksl commented
BTW you could have done as following at your local system:

# find out what's the last commit you added
git log 
# reset these changes, use the last commit not from you here
git reset <commit>
# now all your changes have been reset (i.e. they're still in your source but no longer as commits)
# now make a new commit, where you select which chunks are in it
git commit -p
# repeat until all your changes are in commits again

If github complains because you modified commit after being pushed, you can try the '--force' flag. If that doesn't help, you'll have to make a new PR.